version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts

    ports:
      - ${JENKINS_PORT}:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ${DOCKER_BIN}:/usr/bin/docker
    environment:
      - DOCKER_HOST=tcp://socat:2375
    restart: always

  socat:
    build: socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    expose:
        - "2375"

volumes:
  jenkins_home:
    external: true
